server:
  port: 8084

spring:
  application:
    name: notification-service

  # 👇 CRITICAL: Tells Spring to safely load your hidden passwords
  profiles:
    include: secret

  # 👇 EMAIL CONFIGURATION (Notice we removed username/password placeholders from here)
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}