package com.finvault.notification_service.controller;

import com.finvault.notification_service.dto.TransactionEvent;
import com.finvault.notification_service.service.EmailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class NotificationController {

    @Autowired
    private EmailService emailService;

    @PostMapping("/notifications/send-receipt")
    public String sendTransactionReceipt(@RequestBody TransactionEvent event) {
        System.out.println("📧 REST EVENT RECEIVED: Generating Professional HTML Receipt...");

        String subject = "FinVault Enterprise: Official Transaction Receipt";

        // 👇 Sleek Corporate HTML Template
        String htmlBody = """
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: -apple-system, sans-serif; background-color: #F3F4F6; padding: 20px; }
                    .container { max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.1); border: 1px solid #E5E7EB; }
                    .header { background-color: #0f172a; padding: 25px; color: #ffffff; text-align: center; }
                    .header h1 { margin: 0; font-size: 22px; font-weight: 600; letter-spacing: 1px; }
                    .header span { opacity: 0.5; font-weight: 300; }
                    .content { padding: 30px; color: #1F2937; }
                    .content h2 { margin-top: 0; color: #2563EB; font-size: 18px; border-bottom: 2px solid #E5E7EB; padding-bottom: 10px; }
                    .tx-details { background-color: #F9FAFB; padding: 20px; border-radius: 6px; border: 1px solid #E5E7EB; margin-top: 20px; }
                    .tx-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px dashed #D1D5DB; font-size: 14px; }
                    .tx-row:last-child { border-bottom: none; }
                    .label { font-weight: 600; color: #6B7280; text-transform: uppercase; font-size: 12px; }
                    .value { font-weight: 700; font-family: monospace; font-size: 15px; color: #111827; }
                    .amount { color: #10B981; font-size: 18px; }
                    .footer { background-color: #F9FAFB; padding: 20px; text-align: center; font-size: 11px; color: #9CA3AF; border-top: 1px solid #E5E7EB; line-height: 1.5; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>FINVAULT <span>ENTERPRISE</span></h1>
                    </div>
                    <div class="content">
                        <h2>Transaction Verified ✅</h2>
                        <p style="font-size: 14px; color: #4B5563; line-height: 1.6;">Dear Client,<br><br>Your recent liquidity operation has been successfully processed and recorded on the FinVault secure ledger. Receipt details are below:</p>
                        
                        <div class="tx-details">
                            <div class="tx-row">
                                <span class="label">Transaction Type</span>
                                <span class="value">%s</span>
                            </div>
                            <div class="tx-row">
                                <span class="label">Amount Settled</span>
                                <span class="value amount">₹%s</span>
                            </div>
                            <div class="tx-row">
                                <span class="label">Network Status</span>
                                <span class="value" style="color: #2563EB;">%s</span>
                            </div>
                        </div>
                        
                        <p style="font-size: 12px; color: #6B7280; margin-top: 25px; text-align: center;">If you did not authorize this action, please contact your Institutional Relationship Manager immediately.</p>
                    </div>
                    <div class="footer">
                        Automated alert generated by FinVault Microservices Architecture.<br>
                        Confidential &copy; 2026 FinVault Global Banking
                    </div>
                </div>
            </body>
            </html>
            """.formatted(event.getTransactionType(), event.getAmount(), event.getStatus());

        // Call the new HTML method!
        emailService.sendHtmlEmail("kaifmumtajansari@gmail.com", subject, htmlBody);

        return "Professional Receipt sent successfully!";
    }
}